### ISSUE TITLE
在Application中调用setRequestQueue方法设置缓存路径报错

### ISSUE THREAD

**Issue by yinCheng3161** [kymjs/RxVolley#14]
设置的缓存路径是：
`File httpCacheDirectory = new File(this.getFilesDir() , "httpCache");`
`RxVolley.setRequestQueue(RequestQueue.newRequestQueue(httpCacheDirectory, new OkHttpStack(okHttpClient)));`

异常：
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.kymjs.rxvolley.demo, PID: 4058
                                                 java.lang.RuntimeException: Unable to create application com.kymjs.rxvolley.demo.RxApplication: java.lang.RuntimeException: RequestQueue-> DiskBasedCache cache dir error
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5007)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:179)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                     at android.os.Looper.loop(Looper.java:194)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5795)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1005)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
                                                  Caused by: java.lang.RuntimeException: RequestQueue-> DiskBasedCache cache dir error
                                                     at com.kymjs.rxvolley.http.RequestQueue.newRequestQueue(RequestQueue.java:325)
                                                     at com.kymjs.rxvolley.demo.RxApplication.onCreate(RxApplication.java:53)
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4999)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:179) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                     at android.os.Looper.loop(Looper.java:194) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5795) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1005) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800) `

**Comment by kymjs** [comment]
查看#12 以及检查SD卡读写权限

**Comment by yinCheng3161** [comment]
感谢大神！权限其实添加了的，原因是httpCacheDirectory文件夹并未创建，多加个判断就可以了：
`File httpCacheDirectory = new File(getCacheDir(), "httpCache");
  if (!httpCacheDirectory.exists()){
          httpCacheDirectory.mkdir();
  }`
