### ISSUE TITLE
为什么Android6.0会出现 DiskBasedCache cache dir error错误

### ISSUE THREAD

**Issue by a395726103** [kymjs/RxVolley#34]
为什么Android6.0会出现错误java.lang.RuntimeException: RequestQueue-> DiskBasedCache cache dir error
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                               Caused by: java.lang.RuntimeException: RequestQueue-> DiskBasedCache cache dir error
                                                                  at com.kymjs.rxvolley.http.RequestQueue.newRequestQueue(RequestQueue.java:325)
                                                                  at com.kymjs.rxvolley.http.RequestQueue.newRequestQueue(RequestQueue.java:319)
                                                                  at com.kymjs.rxvolley.RxVolley.getRequestQueue(RxVolley.java:60)

**Comment by kymjs** [comment]
没给存储权限或者没有创建缓存文件夹
