### ISSUE TITLE
DiskBasedCache cache dir error

### ISSUE THREAD

**Issue by LiuGuiLinAndroid** [kymjs/RxVolley#48]
`RequestQueue-> DiskBasedCache cache dir error
java.lang.RuntimeException: RequestQueue-> DiskBasedCache cache dir error
at com.kymjs.rxvolley.http.RequestQueue.newRequestQueue(RequestQueue.java:325)
at com.kymjs.rxvolley.http.RequestQueue.newRequestQueue(RequestQueue.java:319)
at com.kymjs.rxvolley.RxVolley.getRequestQueue(RxVolley.java:61)
at com.kymjs.rxvolley.RxVolley$Builder.doTask(RxVolley.java:305)
at com.kymjs.rxvolley.RxVolley.get(RxVolley.java:310)`

**Comment by kymjs** [comment]
很老的问题了，更新版本
